name: Build workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_token }}

      - name: Build da imagem Docker
        run: |
          docker build \
            -t ${{ secrets.docker_hub_username }}/pagamentos-webhook:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push ${{ secrets.docker_hub_username }}/pagamentos-webhook:latest
