name: Build workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

  # habilita a execução manual do workflow
  workflow_dispatch:

jobs:
  test:
    name: Execução de testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Definição de JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache das dependências
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Execução dos testes
        run: mvn test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_token }}

      - name: Build da imagem Docker
        run: |
          docker build \
            -t ${{ secrets.docker_hub_username }}/pagamentos-webhook:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push ${{ secrets.docker_hub_username }}/pagamentos-webhook:latest
